apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: dapr-subscription
  namespace: vela-system
spec:
  appliesToWorkloads:
  - deployments.apps
  podDisruptive: true
  schematic:
    cue:
      template: |
        parameter: {
          topic: string
          route: string
          pubsubname: string
        }

        outputs: daprSubscription: {
          apiVersion: "dapr.io/v1alpha1"
          kind: "Subscription"
          metadata: {
            name: context.name
            namespace: context.namespace
          }
          spec: {
            topic: parameter.topic
            route: parameter.route
            pubsubname: parameter.pubsubname
          }
          scopes: [
            context.name
          ]
        }