apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: oam-env-default
spec:
  selfSigned: {}

---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: mycomp
spec:
  workload:
    apiVersion: standard.oam.dev/v1alpha1
    kind: PodSpecWorkload
    metadata:
      name: mycomp
      labels:
        workload.oam.dev/type: webservice
    spec:
      podSpec:
        containers:
          - image: crccheck/hello-world
            name: mycomp
            ports:
              - containerPort: 8000
                name: default
                protocol: TCP
      replicas: 1
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: myapp
spec:
  components:
    - componentName: mycomp
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: Route
            metadata:
              labels:
                trait.oam.dev/type: route
            spec:
              host: mycomp.mytest.com
#              backend:
#                port: 8000
              tls:
                issuerName: oam-env-default