---
# Source: cluster-proxy/templates/managedproxyconfiguration.yaml
apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  authentication:
    dump:
      secrets: {}
    signer:
      type: SelfSigned
  proxyServer:
    image: quay.io/open-cluster-management/cluster-proxy:v0.1.4
    namespace: open-cluster-management-addon
    entrypoint:
      type: PortForward
      port: 8091
  proxyAgent:
    image: quay.io/open-cluster-management/cluster-proxy:v0.1.4
