apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevela-io
  namespace: vela-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.oam.dev/component: kubevela-io
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.oam.dev/component: kubevela-io
    spec:
      containers:
      - image: oamdev/kubevela-io:latest
        imagePullPolicy: Always
        name: kubevela-io
        ports:
        - containerPort: 80
          name: port-80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
