apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: canary-demo
  annotations:
    app.oam.dev/publishVersion: v2
spec:
  components:
    - name: canary-demo
      type: webservice
      properties:
        image: barnett/canarydemo:v2
        ports:
          - port: 8090
      traits:
        - type: scaler
          properties:
            replicas: 5
        - type: gateway
          properties:
            domain: canary-demo.com
            http:
              "/version": 8090
  workflow:
    steps:
      - type: canary-deploy
        name: rollout-20
        properties:
          components: [canary-demo]
          weight: 20
          trafficRoutingType: "aliyun-alb"
      - name: suspend
        type: suspend
      - type: canary-deploy
        name: rollout-50
        properties:
          components: [canary-demo]
          weight: 50
          trafficRoutingType: "aliyun-alb"
      - name: suspend-again
        type: suspend
      - type: canary-deploy
        name: rollout-100
        properties:
          components: [canary-demo]
          weight: 100
          trafficRoutingType: "aliyun-alb"

