apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: canary-demo
  annotations:
    app.oam.dev/publishVersion: v2
spec:
  components:
    - name: canary-demo
      type: webservice
      properties:
        image: barnett/canarydemo:v2
        ports:
          - port: 8090
  workflow:
    steps:
      - type: canary-deploy
        name: rollout-20
        properties:
          component: canary-demo
          weight: 20
      - name: check-metrics
        type: check-metrics
        timeout: 5m
        properties:
          query: sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m])) / sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]))
          promAddress: http://promtheus.svc.local:9098
          condition: ">=1"
          duration: 5m
      - type: canary-deploy
        name: rollout-50
        properties:
          component: canary-demo
          weight: 50
      - name: check-metrics
        type: check-metrics
        timeout: 5m
        properties:
          query: sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m])) / sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]))
          promAddress: http://promtheus.svc.local:9098
          condition: ">=1"
          duration: 5m
      - type: canary-deploy
        name: rollout-100
        properties:
          component: canary-demo
          weight: 100

