apiVersion: v1
kind: ConfigMap
metadata:
  name: kruise-rollout-relation
  namespace: vela-system
  labels:
    "rules.oam.dev/resources": "true"
data:
  rules: |-
    - parentResourceType:
        group: rollouts.kruise.io
        kind: Rollout
      childrenResourceType:
        - apiVersion: rollouts.kruise.io/v1alpha1
          kind: BatchRelease
    - parentResourceType:
        group: rollouts.kruise.io
        kind: BatchRelease
      childrenResourceType:
        - apiVersion: apps/v1
          kind: Deployment