apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Deploy crossplane resource and bind secret to clusters
  name: deploy-crossplane-resource
  name: crossplane
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "AWS crossplane RDS Resource"
spec:
  workload:
    definition:
      apiVersion: database.aws.crossplane.io/v1beta1
      kind: RDSInstance
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "database.aws.crossplane.io/v1beta1"
            kind:       "RDSInstance"
            spec: {
                forProvider: {
                    engine:                parameter.engine
                    engineVersion:         parameter.engineVersion
                    dbInstanceClass:       parameter.instanceClass
                    dbInstanceStorageInGB: 20
                    securityIPList:        "0.0.0.0/0"
                    masterUsername:        parameter.username
                    dbSubnetGroupName:     parameter.dbSubnetGroupName
                }
                writeConnectionSecretToRef: {
                    namespace: context.namespace
                    name:      parameter.secretName
                }
                providerConfigRef: {
                    name: "aws-provider"
                }
                deletionPolicy: "Delete"
            }
        }
        parameter: {
            // +usage=RDS engine
            engine: *"mysql" | string
            // +usage=The version of RDS engine
            engineVersion: *"8.0" | string
            // +usage=The instance class for the RDS
            instanceClass: *"db.t2.small" | string
            // +usage=RDS username
            username: string
            // +usage=Secret name which RDS connection will write to
            secretName: string
            // +usage=dbSubnetGroupName
            dbSubnetGroupName: *"mars-subnet-group" | string
        }

