apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: expose
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |-
        parameter: {
          domain: string
          http: [string]: int
        }

        outputs: {
          for k, v in parameter.http {
              "\(k)": {
                  apiVersion: "v1"
                  kind:       "Service"
                  spec: {
                      selector:
                          app: context.name
                      ports: [{
                          port:       v
                          targetPort: v
                      }]
                  }
              }
          }
        }