apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Specify auto scale by annotation"
  name: kautoscale
  namespace: vela-system
spec:
  appliesToWorkloads:
    - webservice # this should be some knative like workload
  schematic:
    cue:
      template: |-
        import "encoding/json"
        patch: {
          metadata: annotations: {
              "my.autoscale.ann": json.Marshal({
                  "minReplicas": parameter.min
                  "maxReplicas": parameter.max
              })
          }
        }
        parameter: {
          min: *1 | int
          max: *3 | int
        }