apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: kubewatch
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Add a watch for resource"
spec:
  appliesToWorkloads:
    - "*"
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: kubewatches.labs.bitnami.com
  extension:
    install:
      helm:
        repo: my-repo
        name: kubewatch
        url: https://wonderflow.info/kubewatch/archives/
        version: 0.1.0    
  schematic:
    cue:
      template: |-
        outputs: watcher:{{
          apiVersion: "labs.bitnami.com/v1alpha1"
          kind:       "KubeWatch"
          spec: handler: webhook: url: parameter.webhook
        }}
        parameter: {
          webhook: string
        }
