apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: webapp
spec:
  components:
    - name: express-server
      type: deployment
      settings:
        image: zzxwill/flask-web-application:v0.3.1-crossplane
        ports: 80
        secretRef:
          - name: db-conn
            environment:
              - username
              - endpoint
              - port

    - name: sample-db
      type: alibaba-rds
      settings:
        name: sample-db
        engine: mysql
        engineVersion: "8.0"
        instanceClass: rds.mysql.c1.large
        username: oamtest
        outputSecretName: db-conn

#    - name: sample-oss
#      type: alibaba-oss
#      settings:
#        name: "sample-oss"
#        engine: "mysql"
#        engineVersion: "8.0"
#        instanceClass: "rds.mysql.c1.large"
#        username: "oam-dev"
#        outputSecretName: db-conn
