---
# Source: cluster-proxy/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:cluster-proxy:addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-proxy:addon-manager
subjects:
  - kind: ServiceAccount
    name: cluster-proxy
    namespace: open-cluster-management-addon
