apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example
  namespace: default
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        port: 8000
        image: docker.io/nginxinc/nginx-unprivileged:latest
  workflow:
    steps:
      # 构建镜像
      - name: apply-comp
        type: apply-component
        properties:
          component: frontend
      # 镜像扫描
      - name: image-scan
        type: trivy-check
        outputs:
          - name: image-scan-result
            valueFrom: result.message
        properties:
          url: http://116.62.199.204:30192/metrics
          image: "docker.io/nginxinc/nginx-unprivileged:latest"
      # 消息通知
      - name: notification
        type: notification
        inputs:
          - from: image-scan-result
            parameterKey: slack.message.text
        if: always
        properties:
          slack:
            url:
              value: https://hooks.slack.com/services/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
