# permissions for end users to edit statefulsetworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulsetworkload-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - statefulsetworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - statefulsetworkloads/status
  verbs:
  - get
