# permissions for end users to view statefulsetworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulsetworkload-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - statefulsetworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - statefulsetworkloads/status
  verbs:
  - get
