apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: autoscalers.standard.oam.dev
spec:
  appliesToWorkloads:
    - webservice
    - backend
    - deployments.apps
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: autoscalers.standard.oam.dev