
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads/status
  verbs:
  - get
- apiGroups:
  - core.oam.dev
  resources:
  - workloaddefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extend.oam.dev
  resources:
  - simplerollouttraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extend.oam.dev
  resources:
  - simplerollouttraits/status
  verbs:
  - get
  - patch
  - update
