# permissions for end users to view simplerollouttraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplerollouttrait-viewer-role
rules:
- apiGroups:
  - extend.oam.dev
  resources:
  - simplerollouttraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extend.oam.dev
  resources:
  - simplerollouttraits/status
  verbs:
  - get
