# permissions for end users to view ingresstraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingresstrait-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - ingresstraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - ingresstraits/status
  verbs:
  - get
