# permissions for end users to edit ingresstraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingresstrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - ingresstraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - ingresstraits/status
  verbs:
  - get
