
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads
  verbs:
  - get
  - list
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads/status
  verbs:
  - get
- apiGroups:
  - core.oam.dev
  resources:
  - ingresstraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - ingresstraits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.oam.dev
  resources:
  - statefulsetworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - statefulsetworkloads/status
  verbs:
  - get
- apiGroups:
  - core.oam.dev
  resources:
  - workloaddefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
