apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: quay.io/open-cluster-management/registration:v0.6.0
  workImagePullSpec: quay.io/open-cluster-management/work:v0.6.0
  placementImagePullSpec: quay.io/open-cluster-management/placement:v0.3.0