apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-cls
spec:
  workload:
    apiVersion: apps.kruise.io/v1alpha1 # the kruise group version
    kind: CloneSet
    metadata:
      name: nginx
    spec:
      # replicas: 1 (TODO: scaler-related trait will handle replicas field)
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:alpine