apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: bookinfo
spec:
  components:
    - componentName: bookinfo-gateway
      traits:
        - trait:
            apiVersion: networking.istio.io/v1alpha3
            kind: VirtualService
            metadata:
              name: bookinfo
            spec:
              hosts:
              - "*"
              gateways:
              - bookinfo-gateway
              http:
              - match:
                - uri:
                    exact: /productpage
                - uri:
                    prefix: /static
                - uri:
                    exact: /login
                - uri:
                    exact: /logout
                - uri:
                    prefix: /api/v1/products
                route:
                - destination:
                    host: productpage
                    port:
                      number: 9080
        - trait:
            apiVersion: networking.istio.io/v1alpha3
            kind: DestinationRule
            metadata:
              name: productpage
            spec:
              host: productpage
              subsets:
                - name: v1
                  labels:
                    version: v1
        - trait:
            apiVersion: networking.istio.io/v1alpha3
            kind: DestinationRule
            metadata:
              name: reviews
            spec:
              host: reviews
              subsets:
                - name: v1
                  labels:
                    version: v1
                - name: v2
                  labels:
                    version: v2
                - name: v3
                  labels:
                    version: v3
