apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: addon-suit
  namespace: vela-system
spec:
  workflowSpec:
    steps:
      - name: vela-prism
        type: addon-operation
        properties:
          addonName: vela-prism
      - name: grafana-definitions
        type: addon-operation
        properties:
          addonName: grafana-definitions
          operation: enable
      - name: prometheus-server
        type: addon-operation
        properties:
          addonName: prometheus-server
          operation: enable
      - name: loki
        type: addon-operation
        properties:
          addonName: loki
          operation: enable
          args:
            - --version=v0.1.2
            - agent=vector
            - serviceType=LoadBalancer
      - name: grafana
        type: addon-operation
        properties:
          addonName: grafana
          operation: enable
          args:
            - serviceType=LoadBalancer
      - name: clean-job
        type: clean-workflow-run-jobs
      - name: print-message
        type: print-message-in-status
        properties:
          message: "All addons have been enabled successfully, you can use 'vela addon list' to check them."
