apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dex
  namespace: vela-system
spec:
  components:
    - name: dex
      type: helm
      properties:
        chart: dex
        version: "0.6.5"
        url: "https://charts.dexidp.io"
        repoType: helm
        values:
          configSecret:
            create: false
            name: dex-config
          envVars:
          - name: DEX_FRONTEND_DIR
            value: /srv/dex/web
          volumeMounts:
          - name: logo-light
            mountPath: /srv/dex/web/themes/light/logo.png
            subPath: logo.png
          - name: favicon-light
            mountPath: /srv/dex/web/themes/light/favicon.png
            subPath: favicon.png
          - name: logo-dark
            mountPath: /srv/dex/web/themes/dark/logo.png
            subPath: logo.png
          - name: favicon-dark
            mountPath: /srv/dex/web/themes/dark/favicon.png
            subPath: favicon.png
          volumes:
          - name: logo-light
            secret:
              secretName: kubevela-logo
              items:
              - key: logo-light
                path: logo.png
          - name: favicon-light
            secret:
              secretName: kubevela-logo
              items:
              - key: favicon-light
                path: favicon.png
          - name: logo-dark
            secret:
              secretName: kubevela-logo
              items:
              - key: logo-dark
                path: logo.png
          - name: favicon-dark
            secret:
              secretName: kubevela-logo
              items:
              - key: favicon-dark
                path: favicon.png