---
# Source: managed-serviceaccount/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:managed-serviceaccount:addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managed-serviceaccount:addon-manager
subjects:
  - kind: ServiceAccount
    name: managed-serviceaccount
    namespace: open-cluster-management-addon
