apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component-deployment
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      # name: nginx-deployment
      labels:
        app: nginx
    spec:
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.14 # changed field 1.17 vs 1.14
            ports:
            - containerPort: 80
