apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloudshell
  namespace: vela-system
spec:
  components:
    - name: cloudshell-operator
      type: helmchart
      properties:
        chart:
          source: cloudtty
          repoURL: https://cloudtty.github.io/cloudtty
          version: "0.3.0"
        release:
          name: cloudshell-operator
          namespace: vela-system
        values:
          image:
            registry: docker.io
            repository: oamdev/cloudshell-operator
            tag: "v0.3.0"
          jobTemplate:
            image:
              registry: docker.io
              repository: oamdev/cloudshell
              tag: "v1.7.2"
