apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloushell
  namespace: vela-system
spec:
  components:
    - name: cloushell-operator
      type: helm
      properties:
        repoType: helm
        url: https://release.daocloud.io/chartrepo/cloudshell
        chart: cloudtty
        version: 0.2.0
        values:
          image:
            registry: hub.kubevela.net
            repository: oamdev/cloudshell-operator
            tag: "v0.2.0"
          jobTemplate:
            image:
              registry: hub.kubevela.net
              repository: oamdev/cloudshell
              tag: "v1.5.0-alpha.2"
