apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: statefulsetworkloads.core.oam.dev
spec:
  definitionRef:
    name: statefulsetworkloads.core.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: StatefulSet
