apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Kubernetes Service"
  name: service
spec:
  appliesToWorkloads:
    - worker
  workloadRefPath: spec.workloadRef
  schematic:
    cue:
      template: |
        outputs: service: {
        	apiVersion: "v1"
        	kind:       "Service"
        	metadata: {
        		name: context.name
        		labels: parameter.labels
        	}
        	spec: {
        		if parameter["ports"] != _|_ {
        			ports: parameter.ports
        		}
        		selector: parameter.labels
        	}
        }
        parameter: {
        	ports?: [...{
        		port: int
        		name: string
        	}]
        	labels: [string]: string
        }
