# permissions for end users to edit horizontalpodautoscalertraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horizontalpodautoscalertrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - horizontalpodautoscalertraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - horizontalpodautoscalertraits/status
  verbs:
  - get
