# permissions for end users to view horizontalpodautoscalertraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horizontalpodautoscalertrait-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - horizontalpodautoscalertraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - horizontalpodautoscalertraits/status
  verbs:
  - get
