# permissions for end users to edit metrichpatraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrichpatrait-editor-role
rules:
- apiGroups:
  - extend.oam.dev
  resources:
  - metrichpatraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extend.oam.dev
  resources:
  - metrichpatraits/status
  verbs:
  - get
