# permissions for end users to view metrichpatraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrichpatrait-viewer-role
rules:
- apiGroups:
  - extend.oam.dev
  resources:
  - metrichpatraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extend.oam.dev
  resources:
  - metrichpatraits/status
  verbs:
  - get
