# permissions for end users to view cronhpatraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronhpatrait-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - cronhpatraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - cronhpatraits/status
  verbs:
  - get
