# permissions for end users to edit cronhpatraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronhpatrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - cronhpatraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - cronhpatraits/status
  verbs:
  - get
