apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: manualscalertrait.core.oam.dev
  annotations:
    oam.appengine.info/apiVersion: "core.oam.dev/v1alpha2"
    oam.appengine.info/kind: "ManualScalerTrait"
spec:
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.ContainerizedWorkload
  definitionRef:
    name: manualscalertraits.core.oam.dev
  extension:
    template: |
      #Template: {
      	apiVersion: "core.oam.dev/v1alpha2"
      	kind:       "ManualScalerTrait"
      	spec: {
      		replicaCount: manualscaler.replica
      	}
      }
      manualscaler: {
      	//+short=r
      	replica: *2 | int
      }
