apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: solr-operator-sample
spec:
  components:
    - type:  solr-cloud
      name: demo-cloud
      properties:
        replicas: 3
        solrImage:
          repository: "library/solr"
          tag: "8.11"
          pullPolicy: IfNotPresent
        zookeeperRef:
          provided:
            image:
              repository: "pravega/zookeeper"
              tag: 0.2.15
              pullPolicy: IfNotPresent
        #solrSecurity:
          #authenticationType: "Basic"
        solrJavaMem: "-Xms1g -Xmx2g"
        solrOpts: "-Dsolr.autoSoftCommit.maxTime=10000"
        solrGCTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
        customSolrKubeOptions:
          podOptions:
            resources:
              limits:
                cpu: "2"
                memory: "10G"
              requests:
                cpu: "500m"
                memory: "4G"