apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create DC/OS Public Agents instance and have conditional
      DC/OS prereqs for gcp
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-public-agents
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/dcos-terraform/terraform-gcp-public-agents.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
