apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: GCP Dns-Module
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-dns-module
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/femnad/terraform-gcp-dns-module.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
