apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Google Kubernetes Engine starter kit to bootstrap
      an e-commerce site based on microservices
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-gke-ecommerce
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/Devgurusio/terraform-gcp-gke-ecommerce.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
