apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: A helm repository
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-helmrepo
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/JamesWoolfenden/terraform-gcp-helmrepo.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
