apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module that creates a service account
      to provide Lacework read-only access to Google Cloud Platform Organizations
      and Projects
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-service-account
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/lacework/terraform-gcp-service-account.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
