apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module for creating VPCs on Google Cloud
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-vpc
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/GMafra/terraform-gcp-vpc.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
