apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: GCP Network-Peering
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-network-peering
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/dcos-terraform/terraform-gcp-network-peering.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
