apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Manages GCP compute engine instance
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-gci
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/rails-on-services/terraform-gcp-gci.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
