apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Lazy GCP instance via Terraform
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-instance-module
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/femnad/terraform-gcp-instance-module.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
