apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Using Terraform to create a regional GKE cluster
      (Hosted Kubernetes offering of GCP)
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-gke-regional
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/woernfl/terraform-gcp-gke-regional.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
