apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: 'IAC for provisioning Infrastructure component
      like network, subnetworks, route '
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-environment-setup
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/karan6190/terraform-gcp-environment-setup.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
