apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module for launching a Service Fabric
      Dev Environment on GCP
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-sfabric
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/Bee-Projects/terraform-gcp-sfabric.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
