apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: A basic terraform module example, which the example
      uses for a helm repo
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-storage
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/JamesWoolfenden/terraform-gcp-storage.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
