apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform gcp memorystore redis example
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-memorystore-redis
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/deepak7093/terraform-gcp-memorystore-redis.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
