apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create DC/OS Master instance and have conditional
      DC/OS Prereqs for GCP
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-masters
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/dcos-terraform/terraform-gcp-masters.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
