apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: ' Terraform module for deploying Elasticsearch
      cluster on GCP'
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-elasticsearch
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/AckeeCZ/terraform-gcp-elasticsearch.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
