apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create an ELB to be used for DC/OS for GCP
  creationTimestamp: null
  labels:
    type: terraform
  name: gcp-compute-firewall
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/dcos-terraform/terraform-gcp-compute-firewall.git
      providerRef:
        name: gcp
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
