apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
  namespace: default
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: docker.io/kennethreitz/httpbin
        ports:
          - port: 80
        cpu: "0.1"
        env:
          - name: FOO
            value: bar
      traits:
          # use expose trait to create a svc
        - type: expose
          properties:
            port:
              - 80
        - type: istio-gateway
          properties:
            hosts:
              - awesomesite.com
            # Default value is ingressgateway which is the default selector for your istio svc
            port: 80
