apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kruise-rollout
  namespace: vela-system
spec:
  components:
    - name: kruise-rollout
      type: helm
      properties:
        repoType: helm
        url: https://openkruise.github.io/charts/
        chart: kruise-rollout
        version: 0.1.1
