apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ocm-cluster-manager
  namespace: vela-system
spec:
  workflow:
    steps:
      - name: apply-ns
        type: apply-component
        properties:
          component: ns-open-cluster-management
      - name: apply-resources
        type: apply-remaining
  components:
    - name: ns-open-cluster-management
      type: raw
      properties:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: open-cluster-management

