apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    custom.definition.oam.dev/alias.config.oam.dev: Helm Repository
    definition.oam.dev/description: Config information to authenticate helm chart repository
  labels:
    custom.definition.oam.dev/ui-hidden: "true"
    custom.definition.oam.dev/catalog.config.oam.dev: velacore-config
    custom.definition.oam.dev/multi-cluster.config.oam.dev: "true"
    custom.definition.oam.dev/type.config.oam.dev: helm-repository
  name: config-helm-repository
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "v1"
        	kind:       "Secret"
        	metadata: {
        		name:      context.name
        		namespace: context.namespace
        		labels: {
        			"config.oam.dev/catalog":       "velacore-config"
        			"config.oam.dev/type":          "helm-repository"
        			"config.oam.dev/multi-cluster": "true"
        			"config.oam.dev/sub-type":      "helm"
        		}
        	}
        	type: "Opaque"
        	stringData: {
        		url: parameter.url
        		if parameter.username != _|_ {
        			username: parameter.username
        		}
        		if parameter.password != _|_ {
        			username: parameter.password
        		}

        	}
        }
        parameter: {
        	// +usage=The public url of the helm chart repository.
        	url: string
        	// +usage=The username of basic auth repo
        	username?: string
        	// +usage=The password of basic auth repo
        	password?: string
        }
  workload:
    type: autodetects.core.oam.dev