apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "A list of strategic merge to kustomize config"
  labels:
    custom.definition.oam.dev/ui-hidden: "true"
  name: kustomize-strategy-merge
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        patch: {
        	spec: {
        		patchesStrategicMerge: parameter.patchesStrategicMerge
        	}
        }

        parameter: {
        	// +usage=a list of strategicmerge, defined as inline yaml objects.
        	patchesStrategicMerge: [...#nestedmap]
        }

        #nestedmap: {
        	...
        }
