apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-asts
spec:
  workload:
    apiVersion: apps.kruise.io/v1alpha1 # the kruise group version
    kind: StatefulSet
    metadata:
      name: nginx
    spec:
      serviceName: nginx-example-asts
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:alpine