---
# Source: managed-serviceaccount/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:managed-serviceaccount:addon-manager
rules:
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons/finalizers
    verbs:
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons/status
    verbs:
      - update
      - patch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons/finalizers
    verbs:
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - addondeploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authentication.open-cluster-management.io
    resources:
      - managedserviceaccounts
      - managedserviceaccounts/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    verbs:
      - approve
      - sign
    resourceNames:
      - kubernetes.io/kube-apiserver-client
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - work.open-cluster-management.io
    resources:
      - manifestworks
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
