# permissions for end users to view sidecartraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecartrait-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - sidecartraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - sidecartraits/status
  verbs:
  - get
