# permissions for end users to edit sidecartraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecartrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - sidecartraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - sidecartraits/status
  verbs:
  - get
