apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Bridgecrew READ ONLY integration module
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-bridgecrew-read-only
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/bridgecrewio/terraform-aws-bridgecrew-read-only.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
