apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: AWS Route53-Cluster-Hostname
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-route53-cluster-hostname
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-route53-cluster-hostname.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
