apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: AWS Eks-Cluster-Autoscaler
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-eks-cluster-autoscaler
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
