apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module creating a Lambda function with
      inline code
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-lambda-with-inline-code
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/babbel/terraform-aws-lambda-with-inline-code.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
