apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module which creates Cloudwatch resources
      on AWS
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-cloudwatch-cis-alarms
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-aws-modules/terraform-aws-cloudwatch.git
      path: modules/cis-alarms
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
