apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module to populate AWS Systems Manager
      (SSM) Parameter Store with values from Terraform. Works great with Chamber.
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-ssm-parameter-store
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-ssm-parameter-store.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
