apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: AWS Rds-Aurora
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-rds-aurora
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
