apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: AWS Lambda-Do-It-All
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-lambda-do-it-all
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/bbeesley/terraform-aws-lambda-do-it-all.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
