apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform Module to Provide an Amazon Simple Notification
      Service (SNS)
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-sns-topic
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-sns-topic.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
