apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: A terraform module to deploy a node problem detector
      on Amazon EKS cluster
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-eks-node-problem-detector
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/lablabs/terraform-aws-eks-node-problem-detector.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
