apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform Module to Provision a Basic IAM System
      User Suitable for CI/CD Systems (E.g. TravisCI, CircleCI)
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-iam-system-user
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-iam-system-user.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
