apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module which creates SNS topic and Lambda
      function which sends notifications to Slack
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-notify-slack
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-aws-modules/terraform-aws-notify-slack.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
