apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform Module to Define Vanity Host/Domain
      (e.g. ) as an ALIAS record
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-route53-alias
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-route53-alias.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
