apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module Terraform module for creating
      AWS IAM Roles with heredocs
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-iam-nofile
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/baikonur-oss/terraform-aws-iam-nofile.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
