apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module to provision a basic IAM user
      with permissions to access S3 resources, e.g. to give the user read/write/delete
      access to the objects in an S3 bucket
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-iam-s3-user
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-iam-s3-user.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
