apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module creating a SecretsManager for
      Rollbar project access tokens
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-secretsmanager-for-rollbar-access-tokens
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/babbel/terraform-aws-secretsmanager-for-rollbar-access-tokens.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
