apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: observability
  namespace: vela-system
spec:
  workflow:
    steps:
      - name: apply-resources
        type: apply-remaining
  components: []