# permissions for end users to edit poddisruptionbudgettraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poddisruptionbudgettrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - poddisruptionbudgettraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - poddisruptionbudgettraits/status
  verbs:
  - get
