# permissions for end users to view poddisruptionbudgettraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poddisruptionbudgettrait-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - poddisruptionbudgettraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - poddisruptionbudgettraits/status
  verbs:
  - get
