# permissions for end users to view serviceexposes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceexpose-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - serviceexposes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - serviceexposes/status
  verbs:
  - get
