# Copyright 2017 Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: bookinfo
spec:
  components:
    - name: details
      type: deployment
      settings:
        serviceAccountName: bookinfo-details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        port: 9080
        labels:
          app: details
          version: v1
        containerName: details
      traits:
        - name: service
          properties:
            ports:
              - port: 9080
                name: http
            labels:
              app: details
            name: details

    - name: ratings
      type: deployment
      settings:
        serviceAccountName: bookinfo-ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
        port: 9080
        labels:
          app: ratings
          version: v1
      traits:
        - name: service
          properties:
            ports:
              - port: 9080
                name: http
            labels:
              app: ratings
            name: ratings

    - name: reviews-v1
      type: deployment
      settings:
        serviceAccountName: bookinfo-reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        port: 9080
        labels:
          app: reviews
          version: v1
        env:
          - name: LOG_DIR
            value: "/tmp/logs"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: wlp-output
            mountPath: /opt/ibm/wlp/output
        containerName: reviews
        volumes:
          - name: wlp-output
          - name: tmp
      traits:
        - name: service
          properties:
            ports:
              - port: 9080
                name: http
            labels:
              app: reviews
            name: reviews

    - name: productpage
      type: deployment
      settings:
        serviceAccountName: bookinfo-productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        port: 9080
        labels:
          app: productpage
          version: v1
        env:
          - name: LOG_DIR
            value: "/tmp/logs"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
        volumes:
          - name: tmp
      traits:
        - name: service
          properties:
            ports:
              - port: 9080
                name: http
            labels:
              app: productpage
            name: productpage
