apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform-based module creates an SLB instance
      under AliCloud's VPC and configures rules
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-slb-rule
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-slb-rule.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
