apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform configuration for Alibaba Cloud Elastic
      Compute Service
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-ecs
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/wonderflow/terraform-alicloud-ecs-instance.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta2
      kind: Configuration
status: {}

