apiVersion: core.oam.dev/v1alpha2
kind: ComponentDefinition
metadata:
  name: alibaba-rds
  namespace: vela-system
  annotations:
    definition.oam.dev/description: Terraform configuration for Alibaba Cloud RDS object
    # identifier of this cloud resource
    cloud-resource/identifier: DB_ID
    # the console url of this cloud resource
    cloud-resource/console-url: "https://rdsnext.console.aliyun.com/detail/{DB_ID}/basicInfo?&region={REGION}"
    # the outputs which are sensitive. Separate them by a comma if there are more than one
    cloud-resource/sensitive-outputs: "DB_PASSWORD"
  labels:
    type: terraform
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        module "rds" {
                  source                     = "github.com/kubevela-contrib/terraform-alicloud-rds"
                  engine                     = "MySQL"
                  engine_version             = "8.0"
                  instance_type              = "rds.mysql.c1.large"
                  instance_storage           = "20"
                  instance_name              = var.instance_name
                  account_name               = var.account_name
                #  privilege                  = "DBOwner"
                  password                   = var.password
                  allocate_public_connection = var.allocate_public_connection
                  security_ips               = var.security_ips
                  databases                  = [
                    {
                      "name" : var.database_name,
                      "character_set" : "utf8",
                      "description" : "test database"
                    },
                  ]
                }

                resource "alicloud_db_account_privilege" "this" {
                  instance_id  = module.rds.db_instance_id
                  account_name = var.account_name
                  privilege    = "ReadWrite"
                  db_names     = [var.database_name]
                }

                output "DB_ID" {
                  value = module.rds.db_instance_id
                }

                output "DB_NAME" {
                  value = module.rds.this_db_instance_name
                }
                output "DB_USER" {
                  value = module.rds.this_db_database_account
                }
                output "DB_PORT" {
                  value = module.rds.this_db_instance_port
                }
                output "DB_HOST" {
                  value = module.rds.this_db_instance_connection_string
                }
                output "DB_PASSWORD" {
                  value = var.password
                }
                output "DB_PUBLIC_HOST" {
                  value = module.rds.db_public_connection_string
                }

                output "DATABASE_NAME" {
                  value = module.rds.this_db_database_name
                }

                variable "instance_name" {
                  description = "RDS instance name"
                  type        = string
                  default     = "poc"
                }

                variable "account_name" {
                  description = "RDS instance user account name"
                  type        = string
                  default     = "oam"
                }

                variable "password" {
                  description = "RDS instance account password"
                  type        = string
                  default     = "Xyfff83jfewGGfaked"
                }

                variable "allocate_public_connection" {
                  description = "Whether to allocate public connection for a RDS instance."
                  type        = bool
                  default     = true
                }

                variable "security_ips" {
                  description = "List of IP addresses allowed to access all databases of an instance"
                  type        = list
                  default     = ["0.0.0.0/0",]
                }

                variable "database_name" {
                  description = "Database name"
                  type        = string
                  default     = "poc"
                }
