apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Create a RabbitMQ based on Terraform module in
      Ali cloud
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-rabbitmq
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-rabbitmq.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
