apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform-based modules are used to create a Private
      Zone on AliCloud, while you can add records to the Zone and associate it with
      a VPC
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-private-zone
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-autoscaling-rule.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
