apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Based on Terraform module, create ECS instances
      on Ali cloud to achieve one-click deployment of cloud marketplace Tensorflow
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-market-tensorflow
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-market-tensorflow.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
