apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform configuration for Alibaba Cloud DNS
  labels:
    type: terraform
  name: alibaba-dns
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-dns.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
