apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: 'Create a lightweight WEB service based on Terraform
      under AliCloud''s VPC, including: VPC, ECS, EIP'
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-vpc-ecs-eip
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-vpc-ecs-eip.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
