apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Alibaba SAE application to be deployed in auto-config
      mode
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-sae-auto-config-application
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/kubevela-contrib/terraform-modules.git
      path: alibaba/sae/auto-config
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
