apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform-based for creating VPC networks in AliCloud
      and creating private network links
  creationTimestamp: null
  labels:
    type: terraform
  name: alibaba-vpc-privatelink-connection
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/terraform-alicloud-modules/terraform-alicloud-vpc-privatelink-connection.git
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
