# permissions for end users to edit servicetraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicetrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - servicetraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - servicetraits/status
  verbs:
  - get
