apiVersion: v1
kind: Service
metadata:
  name: kubevela-io
  namespace: vela-system
spec:
  ports:
  - name: port-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.oam.dev/component: kubevela-io
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
