apiVersion: v1
kind: Service
metadata:
  name: kubevela-io-np
  namespace: vela-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.oam.dev/component: kubevela-io
  sessionAffinity: None
  type: NodePort
