---
# Source: cluster-gateway-addon-manager/templates/clustergatewayconfiguration.yaml
apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ClusterGatewayConfiguration
metadata:
  name: cluster-gateway
spec:
  image: oamdev/cluster-gateway:v1.1.11
  installNamespace: vela-system
  secretNamespace: open-cluster-management-credentials
  secretManagement:
  
    type: ManagedServiceAccount
    managedServiceAccount:
      name: cluster-gateway
  
  egress:
  
    type: ClusterProxy
    clusterProxy:
      proxyServerHost: "proxy-entrypoint.open-cluster-management-addon"
      proxyServerPort: 8090
      credentials:
        namespace: open-cluster-management-addon
        proxyClientCASecretName: proxy-server-ca
        proxyClientSecretName: proxy-client
