---
# Source: cluster-gateway-addon-manager/templates/rolebinder.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:cluster-gateway:role-grantor
  namespace: open-cluster-management-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-gateway:managedcluster-reader
subjects:
  - kind: ServiceAccount
    name: cluster-gateway-addon-manager
    namespace: open-cluster-management-addon
