---
# Source: cluster-gateway-addon-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-gateway-addon-manager
  namespace: open-cluster-management-addon
