apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  name: canary-rollback
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |-
        import ("vela/op")

        parameter: {
          rollbackVersion: string
        }

        comps: op.#Load
        compNames: [ for name, c in comps.value {name}]
        firstcomp: compNames[0]

        apply: op.#ApplyComponent & {
          value: comps.value[firstcomp]
          patch: {
            traits: "rollout": {
              spec: {
                // +patchStrategy=retainKeys
                targetRevisionName: parameter.rollbackVersion
              }
            }

            traits: "virtualService": {
              spec:
                // +patchStrategy=retainKeys
                http: [
                  {
                    route: [{
                      destination: {
                        host:   firstcomp
                        subset: parameter.rollbackVersion
                      }
                      weight: 100
                    }]
                  },
                ]
            }

            traits: "destinationRule": {
              // +patchStrategy=retainKeys
              spec: {
                host: firstcomp
                subsets: [
                  {
                    name: parameter.rollbackVersion
                    labels: {"service.istio.io/canonical-name": parameter.rollbackVersion}
                  },
                ]
              }
            }
          }
        }

        applyRemaining: op.#ApplyRemaining & {
            exceptions: [firstcomp]
        }
