apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: vela-system
  name: crd-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-crd-controller
subjects:
  - kind: ServiceAccount
    name: sa-kustomize-controller
    namespace: vela-system
  - kind: ServiceAccount
    name: sa-helm-controller
    namespace: vela-system
  - kind: ServiceAccount
    name: sa-source-controller
    namespace: vela-system
  - kind: ServiceAccount
    name: sa-image-reflector-controller
    namespace: vela-system
  - kind: ServiceAccount
    name: sa-image-automation-controller
    namespace: vela-system