apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fluxcd
  namespace: vela-system
spec:
  components:
    - name: ns-flux-system
      type: raw
      properties:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: flux-system
